Geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='mainapp')),
    path('products/', include('products.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG == True:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp
from adminapp.views import UserListView, UserCreateView, UserUpdateView, UserDeleteView,\
    ProductsListView, CategoryListView, CategoryCreateView, CategoryUpdateView, CategoryDeleteView
from django.views.decorators.cache import cache_page


app_name = 'adminapp'

urlpatterns = [
    path('users/create/', UserCreateView.as_view(), name='user_create'),
    path('users/read/', UserListView.as_view(), name='users'),
    path('users/update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', CategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', CategoryListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),

    path('products/read/', cache_page(3600)(ProductsListView.as_view()), name='products_list'),
    path('products/read/page/<int:page>/', ProductsListView.as_view(), name='page'),
    path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),

]

authapp/urls.py
from django.urls import path

from .views import login, logout, register, edit, verify

app_name = 'auth'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify')
]

mainapp/urls.py
from django.urls import path

from .views import home, contacts

app_name = 'mainapp'

urlpatterns = [
    path('', home, name='home'),
    path('page/<int:page>/', home, name='page'),
    path('new/', home, name='new'),
    path('contacts/', contacts, name='contacts'),
]

products/urls.py
from django.urls import path

from .views import products, product

app_name = 'products'

urlpatterns = [
    path('', products, name='products'),
    path('category/<int:pk>/', products, name='category'),
    path('product/<int:pk>/', product, name='detail'),
]

adminapp/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='Название')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['pk']

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='Название товара')
    description = models.TextField(blank=True, verbose_name='Описание товара')
    short_description = models.CharField(max_length=60, verbose_name='Краткое описание')
    image = models.ImageField(upload_to='products_images', blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0, verbose_name='Цена товара')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество товара')
    is_active = models.BooleanField(default=True)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ['-updated_at']

    def __str__(self):
        return self.name

adminapp/forms.py
from django import forms

from authapp.models import ShopUser
from authapp.forms import ShopUserEditForm, ShopUserRegisterForm
from products.models import ProductCategory, Product


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = ['username', 'first_name', 'is_active']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'is_active': forms.CheckboxInput(attrs={'class': 'form-control_upd'}),
        }


class UserAdminUpdateForm(forms.ModelForm):
    class Meta:
        model = ShopUser
        fields = ['username', 'first_name', 'last_name', 'is_active', 'email', 'age', 'avatar', 'birth_date', 'promo_accept']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'is_active': forms.CheckboxInput(attrs={'class': 'form-control_upd'}),
            'avatar': forms.FileInput(attrs={'class': 'form-control'})
        }


class ProductCategoryEditForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
            'is_active': forms.CheckboxInput(),
        }


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ProductEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

adminapp/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import user_passes_test
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.utils.decorators import method_decorator

from adminapp.forms import ShopUserAdminEditForm, ProductEditForm, ProductCategoryEditForm, UserAdminUpdateForm
from authapp.forms import ShopUserEditForm, ShopUserRegisterForm

from authapp.models import ShopUser
from products.models import Product, ProductCategory


# @user_passes_test(lambda u: u.is_superuser)
# def users(request):
#     title = 'админка/пользователи'
#     users_list = ShopUser.objects.all().order_by('-is_active', '-is_superuser', '-is_staff', 'username')
#     context = {
#         'title': title,
#         'objects': users_list
#     }
#     return render(request, 'adminapp/users.html', context)


class UserListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UserListView, self).get_context_data(**kwargs)
        context['title'] = 'админка/пользователи'
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super(UserListView, self).dispatch(request, *args, **kwargs)


# @user_passes_test(lambda u: u.is_superuser)
# def user_create(request):
#     title = 'пользователи/cоздание'
#     if request.method == 'POST':
#         user_form = ShopUserRegisterForm(request.POST, request.FILES)
#         if user_form.is_valid():
#             user_form.save()
#             return HttpResponseRedirect(reverse('admin_staff:users'))
#     else:
#         user_form = ShopUserRegisterForm()
#     context = {
#         'title': title,
#         'user_form': user_form,
#     }
#     return render(request, 'adminapp/user_update.html', context)


class UserCreateView(CreateView):
    model = ShopUser
    template_name = 'adminapp/user_create.html'
    form_class = ShopUserRegisterForm
    success_url = reverse_lazy('admin_staff:users')


# @user_passes_test(lambda u: u.is_superuser)
# def user_update(request, pk):
#     title = 'пользователи/редактирование'
#     edit_user = get_object_or_404(ShopUser, pk=pk)
#     if request.method == 'POST':
#         edit_form = ShopUserAdminEditForm(request.POST, request.FILES, instance=edit_user)
#         if edit_form.is_valid():
#             edit_form.save()
#             return HttpResponseRedirect(reverse('admin_staff:users'))
#     else:
#         edit_form = ShopUserAdminEditForm(instance=edit_user)
#     context = {
#         'title': title,
#         'user_form': edit_form,
#     }
#     return render(request, 'adminapp/user_update.html', context)


class UserUpdateView(UpdateView):
    model = ShopUser
    template_name = 'adminapp/user_update.html'
    success_url = reverse_lazy('admin_staff:users')
    form_class = UserAdminUpdateForm

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UserUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'пользователи/редактирование'
        return context


# @user_passes_test(lambda u: u.is_superuser)
# def user_delete(request, pk):
#     title = 'пользователи/удаление'
#     user = get_object_or_404(ShopUser, pk=pk)
#     if request.method == 'POST':
#         user.is_active = False
#         user.save()
#         return HttpResponseRedirect(reverse('admin_staff:users'))
#     context = {
#         'title': title,
#         'user_to_delete': user,
#     }
#     return render(request, 'adminapp/user_delete.html', context)


class UserDeleteView(DeleteView):
    model = ShopUser
    template_name = 'adminapp/user_delete.html'
    context_object_name = 'user_to_delete'
    success_url = reverse_lazy('admin_staff:users')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


# @user_passes_test(lambda u: u.is_superuser)
# def categories(request):
#     title = 'админка/категории'
#     categories_list = ProductCategory.objects.all()
#     context = {
#         'title': title,
#         'objects': categories_list
#     }
#     return render(request, 'adminapp/categories.html', context)


class CategoryListView(ListView):
    model = ProductCategory
    template_name = 'adminapp/categories.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['title'] = 'Админка/категории'
        return context


# @user_passes_test(lambda u: u.is_superuser)
# def category_create(request):
#     title = 'категории/cоздание'
#     if request.method == 'POST':
#         category_form = ProductCategoryEditForm(request.POST)
#         if category_form.is_valid():
#             category_form.save()
#             return HttpResponseRedirect(reverse('admin_staff:categories'))
#     else:
#         category_form = ProductCategoryEditForm()
#     context = {
#         'title': title,
#         'category_form': category_form,
#     }
#     return render(request, 'adminapp/categories_update.html', context)


class CategoryCreateView(CreateView):
    model = ProductCategory
    template_name = 'adminapp/categories_update.html'
    success_url = reverse_lazy('admin_staff:categories')
    form_class = ProductCategoryEditForm

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Категории/создание'
        return context


# @user_passes_test(lambda u: u.is_superuser)
# def category_update(request, pk):
#     title = 'категории/редактирование'
#     edit_category = get_object_or_404(ProductCategory, pk=pk)
#     if request.method == 'POST':
#         edit_form = ProductCategoryEditForm(request.POST, request.FILES, instance=edit_category)
#         if edit_form.is_valid():
#             edit_form.save()
#             return HttpResponseRedirect(reverse('admin_staff:categories'))
#     else:
#         edit_form = ProductCategoryEditForm(instance=edit_category)
#     context = {
#         'title': title,
#         'category_form': edit_form,
#     }
#     return render(request, 'adminapp/categories_update.html', context)


class CategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/categories_update.html'
    success_url = reverse_lazy('admin_staff:categories')
    form_class = ProductCategoryEditForm

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'Категории/редактирование'
        return context


# @user_passes_test(lambda u: u.is_superuser)
# def category_delete(request, pk):
#     title = 'категории/cоздание'
#     category_to_delete = get_object_or_404(ProductCategory, pk=pk)
#     if request.method == 'POST':
#         category_to_delete.is_active = False
#         category_to_delete.save()
#         return HttpResponseRedirect(reverse('admin_staff:categories'))
#     context = {
#         'title': title,
#         'category_to_delete': category_to_delete,
#     }
#     return render(request, 'adminapp/category_delete.html', context)


class CategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category_delete.html'
    success_url = reverse_lazy('admin_staff:categories')
    context_object_name = 'category_to_delete'

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryDeleteView, self).get_context_data(**kwargs)
        context['title'] = 'Категории/удаление'
        return context


# @user_passes_test(lambda u: u.is_superuser)
# def products_list(request, page=1):
#     title = 'админка/товары'
#     context = {'title': title}
#     products_list = Product.objects.all().order_by('name')
#
#     paginator = Paginator(products_list, 3)
#     try:
#         products_paginator = paginator.page(page)
#     except PageNotAnInteger:
#         products_paginator = paginator.page(1)
#     except EmptyPage:
#         products_paginator = paginator.page(paginator.num_pages)
#     context['objects'] = products_paginator
#
#     return render(request, 'adminapp/products_read.html', context)


class ProductsListView(ListView):
    model = Product
    template_name = 'adminapp/products_read.html'
    paginate_by = 4

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductsListView, self).get_context_data(**kwargs)
        context['title'] = 'Адмика/товары'
        return context


@user_passes_test(lambda u: u.is_superuser)
def products(request, pk):
    title = 'админка/продукт'
    category = get_object_or_404(ProductCategory, pk=pk)
    products_list = Product.objects.filter(category__pk=pk).order_by('name')
    context = {
        'title': title,
        'category': category,
        'objects': products_list,
    }
    return render(request, 'adminapp/products.html', context)


@user_passes_test(lambda u: u.is_superuser)
def product_create(request, pk):
    title = 'продукт/cоздание'
    category = get_object_or_404(ProductCategory, pk=pk)
    if request.method == 'POST':
        product_form = ProductEditForm(request.POST, request.FILES)
        if product_form.is_valid():

adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'adminapp/css/style.css' %}">
    <link rel="stylesheet" type="text/css"href='https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css'>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css">

    {% block css %}
    {% endblock %}

    <script src='{% static "adminapp/js/script.js" %}'></script>

    {% block js %}
    {% endblock %}
</head>
<body id="body-pd">
<header class="header" id="header">
    <div class="header_toggle"><i class='bx bx-menu' id="header-toggle"></i></div>
    <div class="header_img"><img src="/media/{{ user.avatar|default:'avatar.png' }}" alt=""></div>
</header>
<div class="l-navbar" id="nav-bar">
    <nav class="nav">
        <div>
            <a href="{% url 'mainapp:home' %}" class="nav_logo">
                <i class='bx bx-home nav_logo-icon'></i>
                <span class="nav_logo-name">Admin`ka</span>
            </a>
            {% include 'adminapp/inludes/inc_admin_menu.html' %}
        </div>
        <a href="{% url 'auth:logout' %}" class="nav_link"> <i class='bx bx-log-out nav_icon'></i> <span class="nav_name">Выход</span> </a>
    </nav>
</div>
<!--Container Main start-->
<div class="height-100 py-2">
    {% block content %}
    {% endblock %}
</div>
<!--Container Main end-->
</body>
</html>

adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Категории товаров</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Категории
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Наименование</th>
                            <th>Товары</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Наименование</th>
                            <th>Товары</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for category in object_list %}
                            <tr {% if not category.is_active %} style="opacity: 0.5;" {% endif %}>
                                <td>{{ category.name }}</td>
                                <td><a href="{% url 'admin_staff:products' category.pk %}">Товары</a></td>
                                <td class="text-center">
                                    <a href="{% url 'admin_staff:category_update' category.pk %}">Edit</a>
                                </td>
                                <td>
                                    <a {% if not category.is_active %} class="invisible" {% endif %} href="{% url 'admin_staff:category_delete' pk=category.pk %}">
                                        <i class="fa fa-times-circle"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'admin_staff:category_create' %}">
                    <button class="btn btn-success">Создать категорию</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}

adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="card mt-3">
    <div class="card-body">
      <h5 class="card-title">{{ object.name }} {% if not object.is_active %}<mark>— товар disabled</mark>{% endif %}</h5>
      <p class="card-text">{{ object.description }}</p>
      <p class="card-text"><small class="text-muted">Доступно на складе — {{ object.quantity }}</small></p>
      <p class="card-text"><small class="text-muted">Цена — {{ object.price }}</small></p>
      <p class="card-text"><small class="text-muted">Категория — {{ object.category }}</small></p>
    </div>
    <img src="{{ object.image.url }}" class="card-img-bottom " style="width: 18rem;" alt="...">
    <div class="row justify-content-end mt-5 mb-2">
      <div class="col-4">
        <button class="btn btn-light">
          <a href="{% url 'admin_staff:products_list' %}">Перейти на главное меню</a>
        </button>
      </div>
      <div class="col-2">
        <button class="btn btn-warning">
          <a href="{% url 'admin_staff:product_update' object.pk %}">Править</a>
        </button>
      </div>
      <div class="col-2">
             <form action="{% url 'admin_staff:product_delete' object.pk %}" method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="удалить">
      </form>
      </div>


    </div>
  </div>


{% endblock %}

adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ update_form }}
      <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
{% endblock %}

adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid mt-3">
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Товары категории: <p class="display-4">{{ category.name|title }}</p>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Наименование</th>
                            <th>Количество</th>
                            <th>Стоимость</th>
                            <th>Детали</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for product in objects %}
                            <tr {% if not product.is_active %} style="opacity: 0.5;" {% endif %}>
                                <td>{{ product.name }}</td>
                                <td>{{ product.quantity }}</td>
                                <td>{{ product.price }}</td>
                                <td class="text-center">
                                    <a href="{% url 'admin_staff:product_read' product.pk %}">Detail</a>
                                </td>
                                <td class="text-center">
                                    <a href="{% url 'admin_staff:product_update' product.pk %}">Edit</a>
                                </td>
                                <td>
                                    <a {% if not product.is_active %} class="invisible" {% endif %} href="{% url 'admin_staff:product_delete' pk=product.id %}">
                                        <i class="fa fa-times-circle"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'admin_staff:product_create' category.pk %}">
                    <button class="btn btn-success">Создать товар</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}

adminapp/templates/adminapp/products_read.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="row container-fluid">
    {% for object in object_list %}
      <div class="card m-2" style="width: 18rem;">
        <img src="{{ object.image.url }}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{ object.name }}</h5>
          {% if object.is_active %}
          <p class="card-text">{{ object.short_description }}</p>
          {% else %}
          <p class="card-text"><mark>Товар неактивен</mark></p>
          {% endif %}
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Цена — {{ object.price }}</li>
          <li class="list-group-item">Количество — {{ object.quantity }}</li>
          <li class="list-group-item">Категория — {{ object.category }}</li>
        </ul>
        <div class="card-body">
          <a href="{% url 'admin_staff:product_update' object.pk %}" class="card-link">Править</a>
          {% if object.is_active %}
          <a href="{% url 'admin_staff:product_delete' pk=object.id %}" class="card-link">Удалить</a>
          {% endif %}
        </div>
      </div>
    {% endfor %}
  </div>
{% if is_paginated %}
  <nav aria-label="Page navigation example" style="margin-top: 30px;">
      <ul class="pagination justify-content-center">
          {% if page_obj.has_previous %}
          <li class="page-item">
              <a class="page-link"
                 href="{% if page_obj.has_previous %} {% url 'adminapp:page' page_obj.previous_page_number %} {% else %} # {% endif %}"
                 aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
              </a>
          </li>
          {% endif %}
          {% for page in page_obj.paginator.page_range %}
          <li class="page-item {% if page_obj.number == page %}active{% endif %}">
              <a class="page-link" href="{% url 'adminapp:page' page %}">{{ page }}</a>
          </li>
          {% endfor %}
          {% if page_obj.has_next %}
          <li class="page-item">
              <a class="page-link"
                 href="{% if page_obj.has_next %} {% url 'adminapp:page' page_obj.next_page_number %} {% else %} # {% endif %}"
                 aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
              </a>
          </li>
          {% endif %}
      </ul>
  </nav>
{% endif %}
{% endblock %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Пользователи</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Пользователи
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Имя пользователя</th>
                                <th>Имя</th>
                                <th>Фамилия</th>
                                <th>Адрес эл. почты</th>
                                <th>Персонал сайта</th>
                                <th>Активный</th>
                                <th>Вход</th>
                                <th>Удалить</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for user in object_list %}
                            <tr {% if not user.is_active %} style="opacity: 0.5; text-decoration: line-through;" {% endif %}>
                                <td><a href="{% url 'admin_staff:user_update' user.id %}" style="color: dodgerblue">{{ user.username }}</a></td>
                                <td>{{ user.first_name }}</td>
                                <td>{{ user.last_name }}</td>
                                <td>{{ user.email }}</td>
                                <td class="text-center">
                                    {% if user.is_staff %}
                                        <i class="fa fa-check-circle"></i>
                                    {% else %}
                                        <i class="fa fa-times-circle"></i>
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                    {% if user.is_active %}
                                        <i class="fa fa-check-circle"></i>
                                    {% else %}
                                        <i class="fa fa-times-circle"></i>
                                    {% endif %}
                                </td>
                                <td>{{ user.last_login }}</td>
                                <td>
                                    <a {% if not user.is_active %} class="invisible" {% endif %} href="{% url 'admin_staff:user_delete' pk=user.id %}">
                                        <i class="fa fa-times-circle"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'adminapp:user_create' %}">
                    <button class="btn btn-success">Создать пользователя</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}