Geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='mainapp')),
    path('products/', include('products.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG == True:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp
from adminapp.views import UserListView, UserCreateView, UserUpdateView, UserDeleteView,\
    ProductsListView, CategoryListView, CategoryCreateView, CategoryUpdateView, CategoryDeleteView
from django.views.decorators.cache import cache_page


app_name = 'adminapp'

urlpatterns = [
    path('users/create/', UserCreateView.as_view(), name='user_create'),
    path('users/read/', UserListView.as_view(), name='users'),
    path('users/update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', CategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', CategoryListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),

    path('products/read/', cache_page(3600)(ProductsListView.as_view()), name='products_list'),
    path('products/read/page/<int:page>/', ProductsListView.as_view(), name='page'),
    path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),

]

authapp/urls.py
from django.urls import path

from .views import login, logout, register, edit, verify

app_name = 'auth'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify')
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='index'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit')
]

mainapp/urls.py
from django.urls import path

from .views import home, contacts

app_name = 'mainapp'

urlpatterns = [
    path('', home, name='home'),
    path('page/<int:page>/', home, name='page'),
    path('new/', home, name='new'),
    path('contacts/', contacts, name='contacts'),
]

ordersapp/urls.py
from django.urls import path

import ordersapp.views as ordersapp

app_name = 'ordersapp'

urlpatterns = [
    path('', ordersapp.OrderList.as_view(), name='orders_list'),
    path('forming/complete/<int:pk>/', ordersapp.order_forming_complete, name='order_forming_complete'),
    path('create/', ordersapp.OrderCreate.as_view(), name='order_create'),
    path('read/<int:pk>/', ordersapp.OrderRead.as_view(), name='order_read'),
    path('update/<int:pk>/', ordersapp.OrderUpdate.as_view(), name='order_update'),
    path('delete/<int:pk>/', ordersapp.OrderDelete.as_view(), name='order_delete'),
]

templates/includes/_main_menu.html
    <a href="{% url 'mainapp:home' %}" class="logo"></a>
    <ul class="menu">
        <li><a href="{% url 'mainapp:home' %}">домой</a></li>
        <li><a href="{% url 'products:products' %}">продукты</a></li>
        <li><a href="{% url 'mainapp:contacts' %}">контакты</a></li>
        <li>
        {% if user.is_authenticated %}
        <li>
            <a href="{% url 'auth:edit' %}">
                {% if user.first_name %}
                    {{ user.first_name }}
                {% else %}
                    {{ user.username }}
                {% endif %}
            </a>
        </li>
        {% endif %}
        {% if user.is_authenticated %}
            <a href="{% url 'auth:logout' %}">выйти</a>
        {% else %}
            <a href="{% url 'auth:login' %}">войти</a>
        {% endif %}
        </li>
        {% if basket %}
        <li>
            <a href="{% url 'basketapp:index' %}">
                {{ basket.0.total_cost|floatformat:0 }} ₽
                /{{ basket.0.total_quantity }} шт/
                </a>
        </li>
        {% endif %}
    </ul>
    <a href="#" class="search"></a>

templates/includes/footer.html
<footer class="pt-5 footer">
    <div class="container">
    <div class="row">
      <div class="col-3">
        <h5 class="text-footer">Контакты</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
        </ul>
      </div>
      <div class="col-3">
        <h5 class="text-footer">Полезная информация</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
        </ul>
      </div>
      <div class="col-4 offset-1">
        <form>
          <h5 class="text-footer">Оставайтесь на связи</h5>
          <p>Подписаться на новости и рассылки</p>
          <div class="d-flex w-100 gap-2">
            <label for="newsletter1" class="visually-hidden">Email address</label>
            <input id="newsletter1" type="text" class="form-control" placeholder="Email address">
            <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
          </div>
        </form>
      </div>
    </div>
    <div class="d-flex justify-content-between py-4 my-4 border-top">
        <p>© 2021 Company, Inc. All rights reserved.</p>
        <ul class="list-unstyled d-flex">
            <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
            <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
            <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
        </ul>
    </div>
    </div>
</footer>

templates/includes/main_menu.html
<nav class="header w-100 pb-4">
    <a href="{% url 'mainapp:home' %}" class="logo"></a>
    <ul class="header_menu">
        <li class="dissapeared"><a href="{% url 'mainapp:home' %}">домой</a></li>
        <li><a href="{% url 'products:products' %}">продукты</a></li>
        <li class="dissapeared"><a href="{% url 'mainapp:contacts' %}">контакты</a></li>
        {% if user.is_authenticated %}
            {% if user.is_superuser %}
            <li class="Sdropdown">
                <a class="dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">
                    <i class="fa fa-american-sign-language-interpreting" aria-hidden="true"></i>
                    Администрирование
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a  class="user dropdown-item" href="{% url 'auth:edit' %}">
                            {% if user.first_name %}
                            <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                                {{ user.first_name }}
                            {% else %}
                            <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                                {{ user.username }}
                            {% endif %}
                        </a>
                    </li>
                    <li>
                        <a class="user dropdown-item" href="{% url 'ordersapp:orders_list' %}">
                            <i class="fa fa-ravelry" aria-hidden="true"></i>
                            Заказы
                        </a>
                    </li>
                    <li><hr class="dropdown-divider"></li>
                    <li>
                        <a class="user dropdown-item" href="{% url 'admin_staff:products_list' %}">
                            <i class="fa fa-gears" aria-hidden="true"></i>
                            Админка
                        </a>
                    </li>
                </ul>
            </li>
            {% else %}
            <li>
                <a  class="user" href="{% url 'auth:edit' %}">
                    {% if user.first_name %}
                    <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                        {{ user.first_name }}
                    {% else %}
                    <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                        {{ user.username }}
                    {% endif %}
                </a>
            </li>
            {% endif %}
        {% endif %}
        {% if user.is_authenticated %}
        <li>
            <a  class="user" href="{% url 'auth:logout' %}">
                <i class="fa fa-sign-out" aria-hidden="true"></i>выйти
            </a>
        {% else %}
            <a href="{% url 'auth:login' %}">
                <i class="fa fa-sign-in" aria-hidden="true"></i>войти
            </a>
        {% endif %}
        </li>
        {% if basket %}
        <li>
            <a  class="user" href="{% url 'basketapp:index' %}">
                <i class="fa fa-shopping-bag" aria-hidden="true"></i>
                {{ basket.0.total_cost|floatformat:0 }} ₽
                ({{ basket.0.total_quantity }} шт)
                </a>
        </li>
        {% endif %}
        <li><a href="#"><i class="fa fa-search" aria-hidden="true"></i></a></li>
    </ul>
</nav>