Geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='mainapp')),
    path('products/', include('products.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG == True:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp
from adminapp.views import UserListView, UserCreateView, UserUpdateView, UserDeleteView,\
    ProductsListView, CategoryListView, CategoryCreateView, CategoryUpdateView, CategoryDeleteView
from django.views.decorators.cache import cache_page


app_name = 'adminapp'

urlpatterns = [
    path('users/create/', UserCreateView.as_view(), name='user_create'),
    path('users/read/', UserListView.as_view(), name='users'),
    path('users/update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', CategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', CategoryListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),

    path('products/read/', cache_page(3600)(ProductsListView.as_view()), name='products_list'),
    path('products/read/page/<int:page>/', ProductsListView.as_view(), name='page'),
    path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),

]

authapp/urls.py
from django.urls import path

from .views import login, logout, register, edit, verify

app_name = 'auth'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify')
]

mainapp/urls.py
from django.urls import path

from .views import home, contacts

app_name = 'mainapp'

urlpatterns = [
    path('', home, name='home'),
    path('page/<int:page>/', home, name='page'),
    path('new/', home, name='new'),
    path('contacts/', contacts, name='contacts'),
]

products/urls.py
from django.urls import path

from .views import products, product

app_name = 'products'

urlpatterns = [
    path('', products, name='products'),
    path('category/<int:pk>/', products, name='category'),
    path('product/<int:pk>/', product, name='detail'),
]

mainapp/models.py
from django.db import models


class Promo(models.Model):
    promo_title = models.CharField(max_length=100, unique=True, verbose_name='promo_title')
    promo_text = models.CharField(max_length=100, unique=True, verbose_name='promo_text')
    promo_slogan = models.CharField(max_length=100, unique=True, verbose_name='promo_slogan')

    def __str__(self):
        return self.promo_title

mainapp/views.py
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from products.models import Product
from mainapp.models import Promo


def home(request, page=1):
    title = 'GeekShop'
    promo = Promo.objects.all()
    context = {
        'title': title,
        'promo': promo,
    }
    products_list = Product.objects.all().order_by(
        'updated_at') if request.resolver_match.url_name == 'new' else Product.objects.all()
    paginator = Paginator(products_list, 3)
    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)
    context['products_list'] = products_paginator
    return render(request, 'mainapp/index.html', context)


def contacts(request):
    title = 'Contacts'
    context = {
        'title': title,
    }
    return render(request, 'mainapp/contact.html', context)

mainapp/templates/mainapp/_index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
	{{ title }}
{% endblock %}
{% block content %}
		<div class="slider">
			<div class="header clearfix">
{% include 'includes/main_menu.html' %}
			</div>
			<div class="text-slider">
				<h3 class="green">тенденции</h3>
				<h3 class="big"> удобные стулья</h3>
				<p>Новый уровень комфорта. Отличные характеристики.</p>
				<a href="#" class="button-order">заказать <img src="{% static 'mainapp/img/arrow.png' %}" alt=""></a>
			</div>	
			<div class="navi">
				<a href="#"></a><a href="#"></a><a href="#"></a>
			</div>
		</div>

		<div class="featured">
			<div class="featured-menu">
					<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
			</div>
			<a class="explore" href="#">показать все <img src="{% static 'mainapp/img/arrow.png' %}" alt=""></a>
			<div class="clearfix">
			</div>
			<div class="tab-content">
				{% for product in products_list %}
				<div class="block">
					<a href="#"><img src="/media/{{ product.image }}" alt="" width="270px" height="270px">
						<div class="text">
							<img src="{% static '/mainapp/img/icon-hover.png' %}" alt="img">
							<h4>{{ product.name }}</h4>
							<p>{{ product.short_description }}</p>
						</div> 
					</a>
				</div>
				{% endfor %}
			</div>
		</div>
{% endblock %}

mainapp/templates/mainapp/contact.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
	{{ title }}
{% endblock %}

{% block content %}
	<section class="contacts container my-4">
		<h1>Наши контакты</h1>
		<div class="row">
			<div class="col-4 card pt-3">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Санкт-Петербург</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах КАД</p>
				</div>
			</div>
			<div class="col-8">
				<div id="map" style="width: 100%; height: 100%"></div>
			</div>
		</div>
	</section>
{% endblock %}
{% block script %}
<script type="text/javascript">
    ymaps.ready(init);
    function init(){
        var myMap = new ymaps.Map("map", {
            center: [60.000911, 30.324537],
            zoom: 17
        });
    }
</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
	{{ title }}
{% endblock %}

{% block content %}
		<header class="header_slider">
			<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
			  <div class="carousel-indicators">
				<button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
				<button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
				<button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
			  </div>
			  <div class="carousel-inner">
			  	{% for el in promo %}
				<div class="carousel-item {% if el.pk == 1 %}active{% endif %}">
					<div class="carousel-item_inner img_{{ el.pk }}">
						<div class="text-slider">
							<h3 class="green">{{ el.promo_title }}</h3>
							<h3 class="big">{{ el.promo_text }}</h3>
							<p>{{ el.promo_slogan }}</p>
							<a href="{% url 'products:products' %}" class="button-order">Каталог</a>
						</div>
					</div>
				</div>
			  	{% endfor %}
			  </div>
			</div>
		</header>

		<main class="container">
			<div class="featured-menu d-flex">
				<a class="{% if request.resolver_match.url_name == 'home' %}active{% endif %} p-2" href="{% url 'mainapp:home' %}">Популярные</a>
				<a class="{% if request.resolver_match.url_name == 'new' %}active{% endif %} p-2"href="{% url 'mainapp:new' %}">Новинки</a>
				<a class="ms-auto p-2" href="{% url 'products:products' %}">показать все ></a>
			</div>

			<div class="tab-content">
				{% for product in products_list %}
				<div class="block">
					<a href="{% url 'products:detail' pk=product.pk %}"><img src="{{ product.image.url }}" alt="" width="270px" height="270px">
						<div class="text">
							<img src="{% static '/mainapp/img/icon-hover.png' %}" alt="img">
							<h4>{{ product.name }}</h4>
							<p>{{ product.short_description }}</p>
						</div> 
					</a>
				</div>
				{% endfor %}
			</div>
			<nav aria-label="Page navigation example">
				<ul class="pagination justify-content-center">
					{% if products_list.has_previous %}
					<li class="page-item">
						<a class="page-link"
						   href="{% url 'mainapp:page' products_list.previous_page_number %}"
						   aria-label="Previous">
							<span aria-hidden="true">&laquo;</span>
						</a>
					</li>
					{% endif %}
					{% for page in products_list.paginator.page_range %}
					<li class="page-item {% if products_list.number == page %}activated{% endif %}">
						<a class="page-link" href="{% url 'mainapp:page' page %}">{{ page }}</a>
					</li>
					{% endfor %}
					{% if products_list.has_next %}
					<li class="page-item">
						<a class="page-link"
						   href="{% url 'mainapp:page' products_list.next_page_number %}"
						   aria-label="Next">
							<span aria-hidden="true">&raquo;</span>
						</a>
					</li>
					{% endif %}
				</ul>
			</nav>
		</main>
{% endblock %}
{% block script %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
{% endblock %}