Geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='mainapp')),
    path('products/', include('products.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG == True:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

authapp/urls.py
from django.urls import path

from .views import login, logout, register, edit, verify

app_name = 'auth'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify')
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='index'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit')
]

products/urls.py
from django.urls import path

from .views import products, product

app_name = 'products'

urlpatterns = [
    path('', products, name='products'),
    path('category/<int:pk>/', products, name='category'),
    path('product/<int:pk>/', product, name='detail'),
]

products/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='Название')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['pk']

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='Название товара')
    description = models.TextField(blank=True, verbose_name='Описание товара')
    short_description = models.CharField(max_length=60, verbose_name='Краткое описание')
    image = models.ImageField(upload_to='products_images', blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0, verbose_name='Цена товара')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество товара')
    is_active = models.BooleanField(default=True)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ['-updated_at']

    def __str__(self):
        return self.name

products/views.py
import random

from django.db import connection
from django.db.models.signals import pre_save
from django.shortcuts import render, get_object_or_404
import os
import json
from django.conf import settings
from django.core.cache import cache
from django.views.decorators.cache import cache_page
from django.dispatch import receiver

from products.models import ProductCategory, Product

SOURCE_DIR = os.path.dirname(__file__)
source_file = os.path.join(SOURCE_DIR, 'static/products.json')


def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True)
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True)


def get_product(pk):
    if settings.LOW_CACHE:
        key = 'products'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_ordered_by_price():
    if settings.LOW_CACHE:
        key = 'products_ordered_by_price'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).order_by('price')


def get_products_in_category_ordered_by_price(pk):
    if settings.LOW_CACHE:
        key = f'products_in_category_ordered_by_price_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category__pk=pk, category__is_active=True).order_by('price')


def get_hot_product():
    products = get_products()
    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)
    if same_products:
        return same_products
    else:
        same_products = Product.objects.all().order_by('price')[:4]
        return same_products


@cache_page(3600)
def products(request, pk=None):
    title = 'Products'
    links_menu = get_links_menu()
    products_json = json.load(open(source_file, encoding='utf-8'))
    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)
    products_list = get_products_ordered_by_price()

    if pk is not None:
        category = get_object_or_404(ProductCategory, pk=pk)
        products_in_category = get_products_in_category_ordered_by_price(pk)

        context = {
            'title': title,
            'links_menu': links_menu,
            'products': products_in_category,
            'category': category,
            'same_products': same_products,
            'hot_product': hot_product
        }
        return render(request, 'products/products.html', context)

    context = {
        'title': title,
        'links_menu': links_menu,
        'products_list': products_list,
        'same_products': same_products,
        'hot_product': hot_product
    }
    return render(request, 'products/products.html', context)


def product(request, pk):
    title = Product.objects.get(pk=pk).name
    context = {
        'title': title,
        'links_menu': get_links_menu(),
        'product': get_product(pk),
    }
    return render(request, 'products/product_detail.html', context)


def db_profile_by_type(prefix, type, queries):
    update_queries = list(filter(lambda x: type in x['sql'], queries))
    print(f'db_profile {type} for {prefix}')
    [print(query['sql']) for query in update_queries]


@receiver(pre_save, sender=ProductCategory)
def product_is_active_update_productcategory_save(sender, instance, **kwargs):
    if instance.pk:
        if instance.is_active:
            instance.product_set.update(is_active=True)
        else:
            instance.product_set.update(is_active=False)

        db_profile_by_type(sender, 'UPDATE', connection.queries)

products/templates/products/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
	{{ title }}
{% endblock %}
{% block css %}
	<link rel="stylesheet" href="{% static 'products/products_style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'mainapp/style_media.css' %}">
{% endblock %}
{% block content %}
            <div class="container my-4">
                <div class="row align-items-start">
                    <div class="col">
                        <div class="description__img">
                            <img src="{{ product.image.url }}">
                            <div class="navi_prod">
                                <a href="#"></a><a href="#"></a><a href="#"></a>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="description__upd">
                            <h3 class="red_upd">горячее предложение</h3>
                            <h3 class="big-bold__upd">{{ product.name }}</h3>
                            <p class="price_upd">за {{ product.price }} ₽</p>
                            <a href="{% url 'basket:add' pk=product.pk %}" class="red-button">
                                заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                            </a>
                            <div class="description-text">
                                <p>{{ product.description }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
{% endblock %}

products/templates/products/products.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
	{{ title }}
{% endblock %}

{% block css %}
	<link rel="stylesheet" href="{% static 'products/products_style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'mainapp/style_media.css' %}">
{% endblock %}

{% block content %}

<main class="details">

{% include 'products/includes/categories_menu.html' %}

{% comment %} block with hot_product {% endcomment %}
	<div class="container my-4">
		<div class="row align-items-start">
			<div class="col">
				<div class="description__img">
					<img src="{{ hot_product.image.url }}">
					<div class="navi_prod">
						<a href="#"></a><a href="#"></a><a href="#"></a>
					</div>
				</div>
			</div>
			<div class="col">
				<div class="description__upd">
					<h3 class="red_upd">горячее предложение</h3>
					<h3 class="big-bold__upd">{{ hot_product.name }}</h3>
					<p class="price_upd">за {{ hot_product.price }} ₽</p>
					<a href="{% url 'basket:add' pk=hot_product.pk %}" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
						<p>{{ hot_product.description }}</p>
					</div>
				</div>
			</div>
		</div>
	</div>

{% comment %} block with product list when category is chosen {% endcomment %}
	{% if category %}
	<div class="related_upd">
		<div class="title_upd">
			<h2>Категория: {{ category.name|title }}</h2>
		</div>
		<div class="related-products_upd">
			{% for product in products %}
			<div class="block">
				<a href="{% url 'products:detail' pk=product.pk %}"><img src="{{ product.image.url }}" alt="" width="368px">
					<div class="text">
						<img src="{% static 'mainapp/img/icon-hover.png' %}" alt="img">
						<h4>{{ product.name }}</h4>
						<p>{{ product.short_description }}</p>
						<p>{{ product.price }} ₽</p>
					</div>
				</a>
			</div>
			{% endfor %}
		</div>
	</div>
	{% endif %}

{% comment %} block with product lists with same products in category or all products {% endcomment %}
	<div class="related_upd same_products">
		{% if category %}
			<div class="title_upd">
				<h2>Похожие товары:</h2>
				<a class="explore_upd" href="{% url 'products:products' %}">показать все ></a>
			</div>
			<div class="tab-content_upd">
				{% for product in same_products %}
				<div class="block">
					<a href="{% url 'products:detail' pk=product.pk %}"><img src="{{ product.image.url }}" alt="" width="270px" height="270px">
						<div class="text">
							<img src="{% static '/mainapp/img/icon-hover.png' %}" alt="img">
							<h4>{{ product.name }}</h4>
							<p>{{ product.short_description }}</p>
						</div>
					</a>
				</div>
				{% endfor %}
			</div>
		{% else %}
			<div class="title_upd">
				<h2>Все товары:</h2>
			</div>
			<div class="tab-content_upd">
				{% for product in products_list %}
					<div class="block">
						<a href="{% url 'products:detail' pk=product.pk %}"><img src="{{ product.image.url }}" alt="" width="270px" height="270px">
							<div class="text">
								<img src="{% static '/mainapp/img/icon-hover.png' %}" alt="img">
								<h4>{{ product.name }}</h4>
								<p>{{ product.short_description }}</p>
							</div>
						</a>
					</div>
				{% endfor %}
			</div>
		{% endif %}
	</div>
</main>
{% endblock %}